### ISSUE TITLE
对于群体重测序、群体遗传学、群体基因组学有什么推荐的书籍

### ISSUE THREAD

**Issue by fengcong3** [shangshanzhizhe/Work_flow_of_population_genetics#1]
你好，
我最近也开始做一些群体方面的工作，但是我对群体分析并不是很了解，请问有什么书籍或者资料可以推荐吗？对于分析背景希望有个了解
谢谢
祝好
奉聪

**Comment by shangshanzhizhe** [comment]
奉聪您好，

群体遗传的基础知识和理论，我推荐Matthew W. Hahn的[Molecular Population Genetics](https://global.oup.com/academic/product/molecular-population-genetics-9780878939657?cc=cn&lang=en&)， 近些年Matthew在分子遗传领域，尤其是物种间渐渗和物种间基因组分化岛屿方面做了很多理论贡献。
另外，群体遗传的分析需要一定的生态学背景知识，这个可以简单参考国内的动物/植物生态学原理教材，简单了解即可，暂无推荐。
最后，建议掌握包括显著性检验，差异统计分析等常用的统计学基础知识，对数据的分析和可靠性检验都很有帮助。
此外，群体遗传学研究中的绘图都是繁琐且冗杂的，建议在绘图时使用R语言，如果您有需要我可以给您推荐一些学习路径。

我也尚且在学习的路上，希望大家共同学习。

祝好！

张上哲
