### ISSUE TITLE
送两个 群体结构  软件  

### ISSUE THREAD

**Issue by hewm2008** [shangshanzhizhe/Work_flow_of_population_genetics#12]
可以搜一下     VCF2PCACluster  VCF2Dis  poplddecay  ldblockshow  ngenomesyn 等等软件
下面送你两程序： 

1.
    vcf2pca  一步到位pca软件  ：  https://github.com/hewm2008/VCF2PCACluster

2  vcf2tree 一步到位tree软件  :    https://github.com/hewm2008/VCF2Dis

**Comment by shangshanzhizhe** [comment]
感谢大佬！
