### ISSUE TITLE
psmc bootstrap

### ISSUE THREAD

**Issue by yanzhongsino** [shangshanzhizhe/Work_flow_of_population_genetics#4]
您好。
使用for循环100遍psmc的命令，for i in {1..100}; do psmc -N25 -t15 -r5 -p "4+25*2+4+6" -o round$i.psmc diploid.psmcfa; done；会得到的100个完全一样的文件，round$i.psmc文件之间没有差别。
这样做bootstrap是不是哪里不对，lh写的seq 100 | xargs -i echo psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o round-{}.psmc split.fa | sh又会报错“Segmentation fault (core dumped)”，可能因为不存在split.fa（只有split.psmcfa）文件导致。

**Comment by shangshanzhizhe** [comment]
您好，抱歉这么久才看见，100次结果应该不会完全一样，这里是做了100次重复计算，最后合并起来。
如果您还需要什么帮助的话可以邮件联系，我们具体看看。
