### ISSUE TITLE
svimmer

### ISSUE THREAD

**Issue by vitty0513** [shangshanzhizhe/Work_flow_of_population_genetics#8]
您好！
我看了一下svimmer的介绍，不太清楚他的具体功能，请问他是取所有数据集的交集，还是简单求并集呢？

谢谢~

**Comment by zhachengwan** [comment]
请问你对这个问题有答案么

**Comment by vitty0513** [comment]
该软件的具体算法我不是很清楚，这是发表该workflow的作者给我的回答：
“我回头看了一样，SVIMMER应该算交集？建立一个SV集合的库，不断读取新的SV条目，如果两者的breakpoint在1kbp范围内，则进行合并，合并后的SV坐标是并集（更靠前的当起始位置，更靠后的当结束位置）”

**Comment by zhachengwan** [comment]
谢谢你的解答，请问你是否遇到一个问题，个体数是3时，num_merged_SVS>3了，我有点不懂这里的原理，请问可以帮我解答一下么？
![image](https://github.com/shangshanzhizhe/Work_flow_of_population_genetics/assets/103158864/36d84aaa-cfd8-4034-87de-3c243905494b)
